title: "André Barbosa de Amaral"
email: bcn.andre@gmail.com
baseurl: ""
url: "https://heyvoon.github.io"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

include:
  - assets/resumes

defaults:
  - scope:
      path: "assets/resumes"
    values:
      permalink: /resume-:basename/

resume:
  en:
    title: "Resume (English)"
    permalink: "/assets/resumes/resume-en/"
  es:
    title: "Resume (Spanish)"
    permalink: "/assets/resumes/resume-es/"
  pt:
    title: "Resume (Portuguese)"
    permalink: "/assets/resumes/resume-pt/"