title: "André Barbosa de Amaral"
email: bcn.andre@gmail.com
baseurl: ""
url: "https://heyvoon.github.io"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
sass_dir: _sass

header_pages:
  - resume-en.md
  - resume-es.md
  - resume-pt.md

resume:
  en:
    title: "Resume (English)"
    permalink: "/resume/resume-en/"
  es:
    title: "Resume (Spanish)"
    permalink: "/resume/resume-es/"
  pt:
    title: "Resume (Portuguese)"
    permalink: "/resume/resume-pt/"