title: "André Barbosa de Amaral - Curriculum Vitae"
baseurl: ""
url: "https://heyvoon.github.io"

# Resume configuration is now handled by _data files and dynamic includes
# The resume files are in assets/resumes/ and are included via Liquid templates