title: "André Barbosa de Amaral"
baseurl: ""
url: "https://andrebarbosacv.github.io"

# Resume configuration is now handled by _data files and dynamic includes
# The resume files are in assets/resumes/ and are included via Liquid templates